---
version: '3'
services:

  api:
    build: ./
    ports: 
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/robertke/orders-service
    command: "CompileDaemon -build='go install ./api' -command=api"